apiVersion: v1
kind: Secret
metadata:
    name: cloudflare
    namespace: kube-system
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:3oTTzIQNgbZ/3WMPP/H7GPiK667zK6C8caDE453dp5MGEg37Fs7pjQ==,iv:+qaXZVTsrvfaNsNnrXNeMjkbgoJK1+mnrZLsw/1ziWs=,tag:nDqoWCh+OxneLfwCeJe3Rw==,type:str]
sops:
    age:
        - recipient: age1em6p85vgjjshlt9urnfnvck9lcekpm5a32t2qfk6tkppep3vfa0sd8dryw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4NEJtSG92YjdUNGFVUmlI
            VHhpcEJkSWE5VmF0cmE4VjlKRWozcGpBUTJZCm1jOFZhMEd2NHBJUEd2OTNMSTBz
            cC9MS05CVHc5TjN1YTF3UVE5Wnd1ZzQKLS0tIDQyWEh3L2djUHh0TE5HcytJSGdi
            TFcvY3p2MURnUlliU0hZTSt0VXJjaXcKKbrcfi2cecqlghLcDOhuA4IXMhqErMOQ
            HxBJrlFWyMcCCDyc1q3cxMsMhGAVl90kzfOGTvI8M2iSGeDurpJyug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-01T15:27:39Z"
    mac: ENC[AES256_GCM,data:aSDK5GyKiOcpqXnBPneD1J5HtROyGjYIGWBfSTgdPcizemnNeTVuL42odyrALs/yQSMzVU+sxv2HHFAYuTEkPxIrJtUEdzW9KhMa4ZfLNr3U30FayDQ2zFLu3z1uW0xP1K7Kb4qXuWgQjFk2JpeUYloTtoXh3wmzgr9ZitGD0lM=,iv:+6FP7ZKPKvcTX/4jg47huVgqqHtEycveDDmp7X6A2pA=,tag:m6IY8PO2DM4any2WEG61Qw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
