apiVersion: v1
kind: Secret
metadata:
    name: cloudflare
    namespace: kube-system
type: Opaque
data:
    token: ENC[AES256_GCM,data:d/rfd+KoHerz6/N5RozwsDgXc1Yjvih+K+uV9KQkFHN3TdPG6ueqxvOL32QfgO/Tvu8hp5C8ytQ=,iv:dhrfui03KShUf9rXJmPEE1JUtjy7Nr1uxWdy6+xEOuM=,tag:WIng/n72WHSVygL3xzqEMA==,type:str]
sops:
    age:
        - recipient: age1em6p85vgjjshlt9urnfnvck9lcekpm5a32t2qfk6tkppep3vfa0sd8dryw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4NEJtSG92YjdUNGFVUmlI
            VHhpcEJkSWE5VmF0cmE4VjlKRWozcGpBUTJZCm1jOFZhMEd2NHBJUEd2OTNMSTBz
            cC9MS05CVHc5TjN1YTF3UVE5Wnd1ZzQKLS0tIDQyWEh3L2djUHh0TE5HcytJSGdi
            TFcvY3p2MURnUlliU0hZTSt0VXJjaXcKKbrcfi2cecqlghLcDOhuA4IXMhqErMOQ
            HxBJrlFWyMcCCDyc1q3cxMsMhGAVl90kzfOGTvI8M2iSGeDurpJyug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-01T14:55:12Z"
    mac: ENC[AES256_GCM,data:2XChc/qtWhcWRQ3HD6g9QJz74ofZ8uS6F/JCTNGrUOvVaQApMmfD/PakYjWb1nE8VEQ7NGhXuI5yQjDT/NZzoE1NkR7S36MYpM/4zPA9PVw/yymKw6zJhy2q9XI6NtH1kmJYSWU0kG/9jdrVFszcRq910xoY5MMh5q+Fz55xEiY=,iv:GGzSckd2btpp9VNPvf6efoSRLPXbh9EUoeO0b08HxRQ=,tag:YWtwT1BBammItGkeji47HA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
