apiVersion: v1
kind: Secret
metadata:
    name: grafana
    namespace: monitoring
type: Opaque
stringData:
    user: ENC[AES256_GCM,data:CxiO5oQ=,iv:YdqLVGmPHo+CaPHNJuoaXDv5WWUJqrswIjdPdosfYrc=,tag:vdLofX+SiJ9BliUJBGwSCA==,type:str]
    password: ENC[AES256_GCM,data:5SWUr96igtHE3aDx9StrQfvW35KZvfSJGwEyaQGIupI=,iv:f4Nu22eHL2EhLIupkldq0wpiILRgDXHNjFdstn/GPVc=,tag:NriVLIBAbZ8d4nK4i8MvNA==,type:str]
sops:
    age:
        - recipient: age1em6p85vgjjshlt9urnfnvck9lcekpm5a32t2qfk6tkppep3vfa0sd8dryw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrbzlKK1VvSitmNkZZa2hh
            L3pBV2dyelZjcU9iaVFWazlqbFRwelpOTUhrCkljT0V1N0FlVDVwcm1tYjhkVng3
            NVlXYXlnY2lwRG5QSW1FcGVyQll1cFEKLS0tIGRyaFNrdGNqMDFLSmdvcWg3UU1K
            RGlZWlpWVnhPR1RaV2grVWNEdjNHbjQKSbm6dCsgY1vnl/Kx92fPMm7sX785BPBJ
            Drac5kwPsJ4h3CsfVZPRkceZQVRP5iBXekrQxK7+9BWKWR52beG4FA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-01T17:25:42Z"
    mac: ENC[AES256_GCM,data:WE+j3lVzdQQl5PKX1rNePdjdbTeY3ySA4kkWJ89P2tLgaa4fjACnbCXc/dE7AXAQT0tj7GC+vcB9AcaqJDhEFrqVfgII8LVc8YbQzdMhVZXcetTKoXyLGoOxTi08iJORPTnNOTpDI3GPxPSJ8GYLXhMqpFEoDqVQL/7QHnlN7+c=,iv:SSEmNrtWyyHqs76ODmXMzM6CRDEw0XL7Ug/vqu5Kl5I=,tag:FF8XuHAD6IwQMP9c4sG0Bg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
