---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: doplace
  labels:
    app: backend
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: doplace
  labels:
    app: backend
spec:
  replicas: 8
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: ghcr.io/do-2k25-28/do-place-backend:v0.0.1-beta.8 # {"$imagepolicy": "flux-system:backend"}
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: http
          env:
            - name: REDIS_HOST
              value: redis.doplace.svc.cluster.local
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_USER
              valueFrom:
                secretKeyRef:
                  name: redis
                  key: username
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis
                  key: password
            - name: FRONTEND_ORIGIN
              value: https://place.polydo.dev
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt
                  key: secret
            - name: HASH_SECRET
              valueFrom:
                secretKeyRef:
                  name: argon2
                  key: secret
            - name: CLUSTER
              value: "true"
          resources:
            requests:
              memory: 512Mi
              cpu: 300m
            limits:
              memory: 1024Mi
              cpu: 600m
