apiVersion: v1
kind: Secret
metadata:
  name: redis
  namespace: doplace
stringData:
  username: ENC[AES256_GCM,data:NFIE3mL28g==,iv:F0MrEPSmkL65S2kBSQfehOs869hy+F0J/HspbSTNZnI=,tag:0YLig7AKGjYTnznFPTT+OA==,type:str]
  password: ENC[AES256_GCM,data:sNbAO/rb7Rdy8eqy71wV4/Yvvcdy6HtEtNzy9/gxyVY=,iv:eu4YkwIE8BREee+XoGjC93H+gYMa+1yVfuBfTfkv0AE=,tag:OwsJ9+yBJxqJhaZW8J+u+g==,type:str]
sops:
  age:
    - recipient: age1e6uew9j5amhht6md5yzcxycj44pmpyarxyezd99fwcrxqjawkvhq5v9r7z
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoYnlRSURxRlBiUEcyYStz
        Vm1JZXNjRHFIZElJdVBZRnhtV1c5ZWVxVG5rClJUZlErR3FaZk1tUGZjSUcxWkxq
        UkQyY0xJaVh0c3FVNm4yYWlKaWV6RXMKLS0tIHB6YlRsbmMyZW9uQ2o2ekZIYjBw
        OENtNTlzVmFiUGRtWlo1QmJUb3pKQW8KqicfgeEDINWJRv/5IDt4tIxc6uCx0LZ9
        /bBzGV3EOVPE355F5I35pftrQG1T7FvdxBIOkg0Nz5qKbi+jC/MI7g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-11T14:44:06Z"
  mac: ENC[AES256_GCM,data:p0hYl246EY5/PJaCYUe8XVWRQ9RBzi0fxhpMV1mYUqamtODWg2Rm6tcBtMhYL6QewZsuaYuy+MMFSdCjCqBgEHa3p4bcLyhCbD4rxUc1tDE/zn6P7ZVaytFgq43e+vsQc2BW87GONEUgTEYWPX3xnrEASvOypQ6zZXhaf1e9s7g=,iv:J+ZWNI4AeFB2aushDbpEnXifFg0M9r2tCD3PJ8CHqA4=,tag:usqFtxq0fPgNBzi2JBjL5Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-acl
  namespace: doplace
type: Opaque
stringData:
  users.acl: ENC[AES256_GCM,data:mOvagQXpOOWgul4U6mD0gnLbmAQH8sMidYH3P0ECJgmBks1lr7O56C9YaW9eei5A0fk3CdRxWukd30yxr9mNlJmREDGwlIC4HGowAoBh2A==,iv:IaRZ9KKLnrIQ4QxR7PHDgGArTnIrVcfB/rfEBe2b03I=,tag:yG7bAhHfVQJasgS8V1meGw==,type:str]
sops:
  age:
    - recipient: age1e6uew9j5amhht6md5yzcxycj44pmpyarxyezd99fwcrxqjawkvhq5v9r7z
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoYnlRSURxRlBiUEcyYStz
        Vm1JZXNjRHFIZElJdVBZRnhtV1c5ZWVxVG5rClJUZlErR3FaZk1tUGZjSUcxWkxq
        UkQyY0xJaVh0c3FVNm4yYWlKaWV6RXMKLS0tIHB6YlRsbmMyZW9uQ2o2ekZIYjBw
        OENtNTlzVmFiUGRtWlo1QmJUb3pKQW8KqicfgeEDINWJRv/5IDt4tIxc6uCx0LZ9
        /bBzGV3EOVPE355F5I35pftrQG1T7FvdxBIOkg0Nz5qKbi+jC/MI7g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-11T14:44:06Z"
  mac: ENC[AES256_GCM,data:p0hYl246EY5/PJaCYUe8XVWRQ9RBzi0fxhpMV1mYUqamtODWg2Rm6tcBtMhYL6QewZsuaYuy+MMFSdCjCqBgEHa3p4bcLyhCbD4rxUc1tDE/zn6P7ZVaytFgq43e+vsQc2BW87GONEUgTEYWPX3xnrEASvOypQ6zZXhaf1e9s7g=,iv:J+ZWNI4AeFB2aushDbpEnXifFg0M9r2tCD3PJ8CHqA4=,tag:usqFtxq0fPgNBzi2JBjL5Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt
  namespace: doplace
stringData:
  secret: ENC[AES256_GCM,data:YWIjjZxVSPptuch0CRmJbtbeeg/WMpI0iAsR6k+xjwg=,iv:RsykBJf0LjC5fC6bhRLic1BVOwnJzJjI9wgTLvivA6w=,tag:+810oV1fw+D3Y9d6/TWnpA==,type:str]
sops:
  age:
    - recipient: age1e6uew9j5amhht6md5yzcxycj44pmpyarxyezd99fwcrxqjawkvhq5v9r7z
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoYnlRSURxRlBiUEcyYStz
        Vm1JZXNjRHFIZElJdVBZRnhtV1c5ZWVxVG5rClJUZlErR3FaZk1tUGZjSUcxWkxq
        UkQyY0xJaVh0c3FVNm4yYWlKaWV6RXMKLS0tIHB6YlRsbmMyZW9uQ2o2ekZIYjBw
        OENtNTlzVmFiUGRtWlo1QmJUb3pKQW8KqicfgeEDINWJRv/5IDt4tIxc6uCx0LZ9
        /bBzGV3EOVPE355F5I35pftrQG1T7FvdxBIOkg0Nz5qKbi+jC/MI7g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-11T14:44:06Z"
  mac: ENC[AES256_GCM,data:p0hYl246EY5/PJaCYUe8XVWRQ9RBzi0fxhpMV1mYUqamtODWg2Rm6tcBtMhYL6QewZsuaYuy+MMFSdCjCqBgEHa3p4bcLyhCbD4rxUc1tDE/zn6P7ZVaytFgq43e+vsQc2BW87GONEUgTEYWPX3xnrEASvOypQ6zZXhaf1e9s7g=,iv:J+ZWNI4AeFB2aushDbpEnXifFg0M9r2tCD3PJ8CHqA4=,tag:usqFtxq0fPgNBzi2JBjL5Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
  name: argon
  namespace: doplace2
stringData:
  secret: ENC[AES256_GCM,data:cWw+JVPmN/lvF4sG+BM5+lJE4T1dEkEyY/C3GdzQ54M=,iv:JFZp17UQvOK/neK2gENISP6UJVids2No721JXCkaRAA=,tag:i3Xwv0DqDr26a8bNIgSCyg==,type:str]
sops:
  age:
    - recipient: age1e6uew9j5amhht6md5yzcxycj44pmpyarxyezd99fwcrxqjawkvhq5v9r7z
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoYnlRSURxRlBiUEcyYStz
        Vm1JZXNjRHFIZElJdVBZRnhtV1c5ZWVxVG5rClJUZlErR3FaZk1tUGZjSUcxWkxq
        UkQyY0xJaVh0c3FVNm4yYWlKaWV6RXMKLS0tIHB6YlRsbmMyZW9uQ2o2ekZIYjBw
        OENtNTlzVmFiUGRtWlo1QmJUb3pKQW8KqicfgeEDINWJRv/5IDt4tIxc6uCx0LZ9
        /bBzGV3EOVPE355F5I35pftrQG1T7FvdxBIOkg0Nz5qKbi+jC/MI7g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-11T14:44:06Z"
  mac: ENC[AES256_GCM,data:p0hYl246EY5/PJaCYUe8XVWRQ9RBzi0fxhpMV1mYUqamtODWg2Rm6tcBtMhYL6QewZsuaYuy+MMFSdCjCqBgEHa3p4bcLyhCbD4rxUc1tDE/zn6P7ZVaytFgq43e+vsQc2BW87GONEUgTEYWPX3xnrEASvOypQ6zZXhaf1e9s7g=,iv:J+ZWNI4AeFB2aushDbpEnXifFg0M9r2tCD3PJ8CHqA4=,tag:usqFtxq0fPgNBzi2JBjL5Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
