---
apiVersion: v1
kind: Secret
metadata:
  name: redis
  namespace: doplace
stringData:
  username: ENC[AES256_GCM,data:5ZCd8XL7fQ==,iv:eHo7VdRLCfSRLywo/mvztOgYbLxibrBMkmTNtT3+Lyc=,tag:fU5Sq9LsxOIZLuDa8dBxVw==,type:str]
  password: ENC[AES256_GCM,data:j+YFGOWWd4xVTUPEEtqb6UeYKcLag+1O8F3lp2cu/WA=,iv:Mqw+vdveMKxKWuPaygOxS7K5lsXvr30GoxdX1KP5rJ8=,tag:ojdrHlL/4NnOrOJfiyospw==,type:str]
sops:
  age:
    - recipient: age1e6uew9j5amhht6md5yzcxycj44pmpyarxyezd99fwcrxqjawkvhq5v9r7z
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIUWRraTlzUjQ4N2lCT09Y
        cGZYL1hoUzVIVW1DNVpiVHUrZ0RDYSsydmpvCmhIakc0RnhqSXJzVHVsNiszWnhH
        VXM4TCtUNzM3ZEd1TDlVL00yK0ttRzAKLS0tIE1SeW9pZHU1NG1DMDZlWjBqbFMw
        ZmlXejUwOHNKcklsa1AyVFdGTlpZdEEK0zjxBS0Its/g652wAzzMBgHpm68uiqbW
        OPDYnQos/rSWa25GOsX4gqTVq3FQSbAHrcvAXg3NoElAG2ioGfvwHg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-11T14:23:55Z"
  mac: ENC[AES256_GCM,data:xJOp0p0hMv2QBq6gLGe0pJd8AW6MehXO2WFfTwaKW0Q0p9dTcAX5b2Z8GZ0ZxmFIY2ZE0b659SHM4t9olhX4ShpMOkfDwormzXQhpznM24LG1SmaxBiU+LFL96imeLUkZ3BlTKGMghR4G0qRV0DZuxfnhBlzXKK7w4OBEEmQ0PE=,iv:OtMHgayYg7tlTuLrGYEhwDqudgPawvmlCl2NsiH0R2I=,tag:vfBFpsghFXmNmWlMytRPhg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt
  namespace: doplace
stringData:
  secret: ENC[AES256_GCM,data:bAoiBTzCb5K0aabPN3jokmUzA+Vg5uP0Ay6nJrY9h4M=,iv:UW/1WMS853/B6J+89WqY8zINLL6RhS7hVfufh4MFvPg=,tag:BtfKh4zFy34noRTofet8WA==,type:str]
sops:
  age:
    - recipient: age1e6uew9j5amhht6md5yzcxycj44pmpyarxyezd99fwcrxqjawkvhq5v9r7z
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIUWRraTlzUjQ4N2lCT09Y
        cGZYL1hoUzVIVW1DNVpiVHUrZ0RDYSsydmpvCmhIakc0RnhqSXJzVHVsNiszWnhH
        VXM4TCtUNzM3ZEd1TDlVL00yK0ttRzAKLS0tIE1SeW9pZHU1NG1DMDZlWjBqbFMw
        ZmlXejUwOHNKcklsa1AyVFdGTlpZdEEK0zjxBS0Its/g652wAzzMBgHpm68uiqbW
        OPDYnQos/rSWa25GOsX4gqTVq3FQSbAHrcvAXg3NoElAG2ioGfvwHg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-11T14:23:55Z"
  mac: ENC[AES256_GCM,data:xJOp0p0hMv2QBq6gLGe0pJd8AW6MehXO2WFfTwaKW0Q0p9dTcAX5b2Z8GZ0ZxmFIY2ZE0b659SHM4t9olhX4ShpMOkfDwormzXQhpznM24LG1SmaxBiU+LFL96imeLUkZ3BlTKGMghR4G0qRV0DZuxfnhBlzXKK7w4OBEEmQ0PE=,iv:OtMHgayYg7tlTuLrGYEhwDqudgPawvmlCl2NsiH0R2I=,tag:vfBFpsghFXmNmWlMytRPhg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
  name: argon2
  namespace: doplace
stringData:
  secret: ENC[AES256_GCM,data:aHLVILxVpI+75aWTgBY8HQU0QRLvQhsoJCQyLlY1Ey8=,iv:vLg55FX5RD7AOLuOHmLEK6m14ZNOQrCo+zJDk2HR9GY=,tag:8kqOyuG2qMA+BeaZRComUw==,type:str]
sops:
  age:
    - recipient: age1e6uew9j5amhht6md5yzcxycj44pmpyarxyezd99fwcrxqjawkvhq5v9r7z
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIUWRraTlzUjQ4N2lCT09Y
        cGZYL1hoUzVIVW1DNVpiVHUrZ0RDYSsydmpvCmhIakc0RnhqSXJzVHVsNiszWnhH
        VXM4TCtUNzM3ZEd1TDlVL00yK0ttRzAKLS0tIE1SeW9pZHU1NG1DMDZlWjBqbFMw
        ZmlXejUwOHNKcklsa1AyVFdGTlpZdEEK0zjxBS0Its/g652wAzzMBgHpm68uiqbW
        OPDYnQos/rSWa25GOsX4gqTVq3FQSbAHrcvAXg3NoElAG2ioGfvwHg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-11T14:23:55Z"
  mac: ENC[AES256_GCM,data:xJOp0p0hMv2QBq6gLGe0pJd8AW6MehXO2WFfTwaKW0Q0p9dTcAX5b2Z8GZ0ZxmFIY2ZE0b659SHM4t9olhX4ShpMOkfDwormzXQhpznM24LG1SmaxBiU+LFL96imeLUkZ3BlTKGMghR4G0qRV0DZuxfnhBlzXKK7w4OBEEmQ0PE=,iv:OtMHgayYg7tlTuLrGYEhwDqudgPawvmlCl2NsiH0R2I=,tag:vfBFpsghFXmNmWlMytRPhg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
