apiVersion: v1
kind: Secret
metadata:
  name: gitlab-registry
  namespace: messagerie
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6IHsiZ2l0bGFiLnBvbHl0ZWNoLnVtb250cGVsbGllci5mciI6IHsidXNlcm5hbWUiOiAiZ2l0bGFiK2RlcGxveS10b2tlbi01MSIsICJwYXNzd29yZCI6ICJnbGR0LWVNeEgtZExwZFRtTDJ4Z1Y3cHlqIiwgImVtYWlsIjogIiIsICJhdXRoIjogIloybDBiR0ZpSzJSbGNHeHZlUzEwYjJ0bGJpMDFNVHBuYkdSMExXVk5lRWd0WkV4d1pGUnRUREo0WjFZM2NIbHEifX19
