---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: keepalived
  namespace: kube-system
spec:
  interval: 1h
  url: oci://ghcr.io/itrooz/helm-charts/keepalived
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    semver: 'v0.1.0'
