apiVersion: v1
kind: Secret
metadata:
    name: grafana
    namespace: monitoring
stringData:
    user: ENC[AES256_GCM,data:1ZoLs+I=,iv:ailOVCODmB4jBmP/6UAlBiSILZtxorDHUc7uV15FV4s=,tag:RxHJXWGmcHV0rNQ5EYC5Ig==,type:str]
    password: ENC[AES256_GCM,data:bn47Texavw0dGhkrm0iEuywe/n3TI2Tem5Qwo856QWI=,iv:KcbVVkWJb0mAUVsjGq4buXMAxNvzVRMum7UqK3gk21A=,tag:TIRTYLMYeCrUL7YZ4uBLPg==,type:str]
sops:
    age:
        - recipient: age1e6uew9j5amhht6md5yzcxycj44pmpyarxyezd99fwcrxqjawkvhq5v9r7z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEeDU0TWQzQVVEOVdSbENh
            cDRoRlgzTUkwNnNyN09rZXRsSy9ud0d6K1VNCm1lWWhQM2duUHo0eXp0cVgzMytE
            WG95ZElBYTdhNWhtQ1lIMWQrNFdGOEUKLS0tIEdlTFZ3ZXpqbzh4VTlMQ3l5K1Zw
            TTZtUE5HMFJ5VngySG5ZOEZTMm82SmMK+Bs80uPNWLc7k3G9gMc1NSYkHJIOH5j1
            UiIL27zOlSiF6lgdJq3vlYQC5TqKokryIZqeS01G3TtwKfIyd9xugg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-16T10:55:45Z"
    mac: ENC[AES256_GCM,data:2amfLc3GD1ZPJnfU/s355un5oRXj/Hi5QH1fie+4Ice5On8Bio6nAB4pKkD3DtkCBrPXqdKLYWHuI1yeW/PfH8XzI/P0pDkSvjiTfH98fKsMDfyVmPaczN05vsAHFCJmhSJLlZ+J1BR188b5mgTzehMoaefB021VRdY0qXDavDw=,iv:O1OR9kurPWKjpsmGUQmJ8dmonMlUfQDg7c0P4LCocU8=,tag:gxTTOpF4SKUM7VKPfo5B1A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: kube-prometheus-stack
    namespace: monitoring
spec:
    interval: 1h
    timeout: 5m
    chart:
        spec:
            chart: kube-prometheus-stack
            version: 79.5.0
            sourceRef:
                kind: HelmRepository
                name: prometheus
                namespace: monitoring
            interval: 5m
    releaseName: kube-prometheus-stack
    values:
        alertmanager:
            enabled: false
        grafana:
            admin:
                existingSecret: grafana
                userKey: user
                passwordKey: password
            ingress:
                enabled: true
                hosts:
                    - grafana.polydo.dev
                tls:
                    - secretName: cloudflare-origin-cert
                      hosts:
                        - grafana.polydo.dev
        prometheus:
            prometheusSpec:
                replicas: 2
                podAntiAffinity: hard
sops:
    age:
        - recipient: age1e6uew9j5amhht6md5yzcxycj44pmpyarxyezd99fwcrxqjawkvhq5v9r7z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEeDU0TWQzQVVEOVdSbENh
            cDRoRlgzTUkwNnNyN09rZXRsSy9ud0d6K1VNCm1lWWhQM2duUHo0eXp0cVgzMytE
            WG95ZElBYTdhNWhtQ1lIMWQrNFdGOEUKLS0tIEdlTFZ3ZXpqbzh4VTlMQ3l5K1Zw
            TTZtUE5HMFJ5VngySG5ZOEZTMm82SmMK+Bs80uPNWLc7k3G9gMc1NSYkHJIOH5j1
            UiIL27zOlSiF6lgdJq3vlYQC5TqKokryIZqeS01G3TtwKfIyd9xugg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-16T10:55:45Z"
    mac: ENC[AES256_GCM,data:2amfLc3GD1ZPJnfU/s355un5oRXj/Hi5QH1fie+4Ice5On8Bio6nAB4pKkD3DtkCBrPXqdKLYWHuI1yeW/PfH8XzI/P0pDkSvjiTfH98fKsMDfyVmPaczN05vsAHFCJmhSJLlZ+J1BR188b5mgTzehMoaefB021VRdY0qXDavDw=,iv:O1OR9kurPWKjpsmGUQmJ8dmonMlUfQDg7c0P4LCocU8=,tag:gxTTOpF4SKUM7VKPfo5B1A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
