apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: velocity
  namespace: minecraft
spec:
  interval: 1h
  timeout: 5m
  chart:
    spec:
      chart: minecraft-proxy
      version: '3.9.0'
      sourceRef:
        kind: HelmRepository
        name: minecraft-server-charts
        namespace: minecraft
      interval: 5m
  releaseName: velocity
  values:
    image:
      repository: itzg/mc-proxy
    minecraftProxy:
      type: VELOCITY
      velocityVersion: 3.4.0-SNAPSHOT
