apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: uptime-kuma
  namespace: monitoring
spec:
  interval: 1h
  timeout: 5m
  chart:
    spec:
      chart: uptime-kuma
      version: '2.22.0'
      sourceRef:
        kind: HelmRepository
        name: uptime-kuma
        namespace: monitoring
      interval: 5m
  releaseName: uptime-kuma
  values:
    ingress:
      enabled: true
      hosts:
        - host: uptime.polydo.dev
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - secretName: cloudflare-origin-cert
          hosts:
            - uptime.polydo.dev
